development:
 adapter: redis
 url: redis://localhost:6379/1

test:
 adapter: async

production:
 adapter: redis
 url: redis://redistogo:314fc64f78462a3a949c3d92e968c21c@crestfish.redistogo.com:10796/
 #heroku action_cable
 #change this url, because this one belongs to alejandro
